[tools]
node = "22.16.0"
"github:JohnnyMorganz/luau-lsp" = "1.68.1"
"aqua:JohnnyMorganz/StyLua" = "2.5.2"
"github:UpliftGames/wally" = "0.3.2"
"github:luau-lang/lute" = "1.0.0"
"github:lutest-dev/lutest" = "0.7.1"
"github:pesde-pkg/pesde" = "0.7.3"
"github:lune-org/lune" = "0.10.5"
"github:rojo-rbx/rojo" = "7.7.0"
"http:chafa" = { version = "1.18.2", url = "https://hpjansson.org/chafa/releases/static/chafa-1.18.2-1-x86_64-windows.zip" }

[tasks.rojo-serve]
hide = true
run = "rojo serve dev.project.json"

[tasks.rojo-sourcemap]
hide = true
run = "rojo sourcemap dev.project.json --output sourcemap.json --watch"

[tasks.dev]
description = "Serve the development project and watch its sourcemap"
depends = ["rojo-serve", "rojo-sourcemap"]

[tasks.setup]
description = "Install project tools and development dependencies"
run = ["mise install", "pesde install", "wally install"]
