[package]
name = "cayasde/ok"
description = "A compact assertion and mock library for Luau and Roblox."
version = "1.0.1"
license = "MIT"
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
include = ["default.project.json", "src", "src/**", "wally.toml"]
exclude = ["**"]

[dependencies]

[dev-dependencies]
t = "cayasde/lutest@0.7.1"
